
import { Fabric, Gender, Measurements, GarmentStyle, FabricColor, PatternDesign, StyleItem, PricingRule, Order, CollarType, SleeveType, PricingPlan, User, UserRole } from './types';

export const TRANSLATIONS = {
  ar: {
    nextStep: 'الخطوة التالية',
    nextToSizes: 'التالي: إدخال المقاسات',
    nextToStyles: 'التالي: اختيار الموديل', // Updated logic order
    nextToFabrics: 'التالي: اختيار القماش', // Updated logic order
    nextToPattern: 'التالي: عرض البترون',
    nextToExport: 'التالي: قائمة التصدير',
    nextToPay: 'التالي: الدفع والتأكيد',
    backToHome: 'العودة للرئيسية',
    switchLang: 'English',
    journeyTitle: 'رحلة التفصيل الذكية',
    journeyDesc: 'ابدأ تصميم قطعتك خطوة بخطوة من الصفر',
    // New Section Titles
    personalDesignerTitle: 'التفصيل مع المصمم الخاص',
    personalDesignerDesc: 'تواصل مباشرة مع مدير حسابك عبر الرمز الخاص',
    mainDesignerTitle: 'المصمم الرئيسي',
    mainDesignerDesc: 'صمم بنفسك: اختر الموديل، القماش، والمقاسات بحرية',
    // ---
    measurementsTitle: 'المصمم الرئيسي - المقاسات',
    measurementsDesc: 'الخطوة 2: أدخل المقاسات بدقة لضمان أفضل نتيجة للبترون',
    devDashboard: 'قسم المطور',
    devDesc: 'إدارة النظام، الإعدادات، والبيانات',
    genderSelect: 'الخطوة 1: اختيار الجنس',
    male: 'رجالي',
    female: 'نسائي',
    children: 'أطفال',
    maleDesc: 'بترونات كلاسيكية ورسمية',
    femaleDesc: 'أناقة وتفاصيل فنية ناعمة',
    childrenDesc: 'تصاميم مريحة وعملية',
    fabricLib: 'الخطوة 4: اختيار القماش',
    fabricDesc: 'اختر النسيج الذي يتناسب مع الموديل والمقاسات المختارة',
    thickness: 'مستوى السماكة',
    stretch: 'المرونة',
    breathability: 'المسامية',
    durability: 'المتانة',
    colorCategory: 'التصنيف',
    patternTexture: 'النقشة والخامة',
    styleSelect: 'الخطوة 3: اختيار الموديل',
    exportTitle: 'الخطوة 6: قائمة التصدير',
    exportDesc: 'تم تجهيز البترون والملفات التقنية. اختر التنسيق المناسب.',
    pdfExport: 'ملف PDF فني',
    excelExport: 'ملف Excel / CSV',
    svgExport: 'بترون Vector SVG',
    finishSave: 'إنهاء وحفظ في السجل',
    downloadNow: 'تحميل الآن',
    standardSizes: 'مقاسات جاهزة',
    advancedMethod: 'المنهج الفني',
    archives: 'الأرشيف',
    saveMeasurements: 'حفظ القياسات',
    uploadPhoto: 'إرفاق صورة مرجعية',
    clientPhoto: 'صورة العميل / الموديل',
    blueprint: 'تخطيط هندسي',
    profileName: 'اسم الملف الشخصي...',
    noProfiles: 'لا توجد ملفات مقاسات محفوظة',
    use: 'استخدام',
    logout: 'خروج',
    paymentTitle: 'الخطوة 7: تأكيد الطلب والدفع',
    paymentDesc: 'مراجعة نهائية للطلب وإدخال بيانات الشحن.',
    customerInfo: 'بيانات العميل',
    fullName: 'الاسم الكامل',
    phoneNumber: 'رقم الهاتف',
    address: 'العنوان بالتفصيل',
    paymentMethod: 'وسيلة الدفع',
    creditCard: 'بطاقة ائتمان / مدى',
    cashOnDelivery: 'الدفع عند الاستلام',
    orderSummary: 'ملخص الطلب',
    totalPrice: 'السعر الإجمالي',
    confirmOrder: 'تأكيد الطلب وإرساله',
    proceedToPayment: 'متابعة للدفع وإنهاء الطلب',
    currency: 'ر.س',
    enterCodeTitle: 'تفعيل المصمم الخاص',
    enterCodeDesc: 'أدخل رمز المدير للوصول إلى قسم "التفصيل مع المصمم الخاص"',
    codePlaceholder: 'أدخل الرمز (مثال: X7B9A2)',
    validateCode: 'تفعيل الرمز',
    invalidCode: 'الرمز غير صحيح، يرجى المحاولة مرة أخرى',
    shoppingWith: 'أنت متصل بالمصمم الخاص:',
    changeManager: 'إلغاء الربط'
  },
  en: {
    nextStep: 'Next Step',
    nextToSizes: 'Next: Measurements',
    nextToStyles: 'Next: Select Style',
    nextToFabrics: 'Next: Select Fabric',
    nextToPattern: 'Next: Pattern View',
    nextToExport: 'Next: Export Data',
    nextToPay: 'Next: Payment & Confirm',
    backToHome: 'Back to Home',
    switchLang: 'العربية',
    journeyTitle: 'Smart Tailoring Journey',
    journeyDesc: 'Start designing your piece step by step from scratch',
    // New Section Titles
    personalDesignerTitle: 'Tailoring with Personal Designer',
    personalDesignerDesc: 'Connect with your manager using a specialized code',
    mainDesignerTitle: 'Main Designer Section',
    mainDesignerDesc: 'Design freely: Choose styles, fabrics, and sizes yourself',
    // ---
    measurementsTitle: 'Main Designer - Measurements',
    measurementsDesc: 'Step 2: Input measurements for accurate pattern generation',
    devDashboard: 'Developer Section',
    devDesc: 'System management, settings, and data',
    genderSelect: 'Step 1: Select Gender',
    male: 'Men',
    female: 'Women',
    children: 'Children',
    maleDesc: 'Classic and formal patterns',
    femaleDesc: 'Elegance and soft artistic details',
    childrenDesc: 'Comfortable and practical designs',
    fabricLib: 'Step 4: Fabric Library',
    fabricDesc: 'Choose the fabric that matches your chosen style',
    thickness: 'Thickness Level',
    stretch: 'Stretch',
    breathability: 'Breathability',
    durability: 'Durability',
    colorCategory: 'Category',
    patternTexture: 'Pattern & Texture',
    styleSelect: 'Step 3: Select Style',
    exportTitle: 'Step 6: Export Files',
    exportDesc: 'Pattern and technical data ready. Choose format.',
    pdfExport: 'Technical PDF',
    excelExport: 'Excel / CSV File',
    svgExport: 'Vector SVG Pattern',
    finishSave: 'Finish & Save to Log',
    downloadNow: 'Download Now',
    standardSizes: 'Standard Sizes',
    advancedMethod: 'Technical Method',
    archives: 'Archives',
    saveMeasurements: 'Save Measurements',
    uploadPhoto: 'Attach Reference Photo',
    clientPhoto: 'Client / Model Photo',
    blueprint: 'Engineering Blueprint',
    profileName: 'Profile name...',
    noProfiles: 'No saved measurement profiles',
    use: 'Use',
    logout: 'Logout',
    paymentTitle: 'Step 7: Payment & Confirm',
    paymentDesc: 'Final review and shipping details.',
    customerInfo: 'Customer Information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    address: 'Detailed Address',
    paymentMethod: 'Payment Method',
    creditCard: 'Credit Card / Mada',
    cashOnDelivery: 'Cash on Delivery',
    orderSummary: 'Order Summary',
    totalPrice: 'Total Price',
    confirmOrder: 'Confirm & Place Order',
    proceedToPayment: 'Proceed to Payment',
    currency: 'SAR',
    enterCodeTitle: 'Activate Personal Designer',
    enterCodeDesc: 'Enter manager code to access "Personal Designer" section',
    codePlaceholder: 'Enter code (e.g., X7B9A2)',
    validateCode: 'Activate Code',
    invalidCode: 'Invalid code, please try again',
    shoppingWith: 'Connected to Personal Designer:',
    changeManager: 'Unlink'
  }
};

export const STANDARD_SIZES: Record<string, Measurements> = {
  'S': { height: 165, chest: 88, waist: 72, hips: 94, shoulderWidth: 38, armLength: 58, neckCircumference: 36, backLength: 40, waistToHip: 18, waistToFloor: 100 },
  'M': { height: 170, chest: 96, waist: 80, hips: 102, shoulderWidth: 40, armLength: 60, neckCircumference: 38, backLength: 42, waistToHip: 20, waistToFloor: 102 },
  'L': { height: 175, chest: 104, waist: 88, hips: 110, shoulderWidth: 42, armLength: 62, neckCircumference: 40, backLength: 44, waistToHip: 22, waistToFloor: 104 },
  'XL': { height: 180, chest: 112, waist: 98, hips: 118, shoulderWidth: 44, armLength: 64, neckCircumference: 42, backLength: 46, waistToHip: 24, waistToFloor: 106 },
};

export const CHILDREN_SIZES: Record<string, Measurements> = {
  '4Y': { height: 104, chest: 56, waist: 53, hips: 60, shoulderWidth: 26, armLength: 36, neckCircumference: 26, backLength: 25, waistToHip: 10, waistToFloor: 60 },
  '6Y': { height: 116, chest: 60, waist: 56, hips: 64, shoulderWidth: 28, armLength: 40, neckCircumference: 28, backLength: 27, waistToHip: 11, waistToFloor: 68 },
  '8Y': { height: 128, chest: 64, waist: 59, hips: 68, shoulderWidth: 30, armLength: 44, neckCircumference: 30, backLength: 29, waistToHip: 12, waistToFloor: 76 },
};

export const INITIAL_FABRICS: Fabric[] = [
  {
    id: 'cotton-egyptian',
    name: 'قطن مصري فاخر',
    description: 'قطن طويل التيلة عالي الجودة، يتميز بالنعومة والمتانة العالية.',
    color: '#F5F5F5',
    thickness: 'medium',
    material: 'Cotton',
    image: 'https://images.unsplash.com/photo-1598300056393-54d61434984f?auto=format&fit=crop&q=80&w=300',
    properties: { stretch: 'منخفضة', breathability: 'عالية', durability: 'عالية' },
    physics: { mass: 0.8, stiffness: 0.2, damping: 0.1 }
  },
  {
    id: 'silk-satin',
    name: 'حرير ساتان',
    description: 'نسيج فاخر بلمعة طبيعية وملمس ناعم جداً، ينساب بانسيابية.',
    color: '#E0E0E0',
    thickness: 'thin',
    material: 'Silk',
    image: 'https://images.unsplash.com/photo-1612450630138-c64e525a7404?auto=format&fit=crop&q=80&w=300',
    properties: { stretch: 'منخفضة', breathability: 'متوسطة', durability: 'متوسطة' },
    physics: { mass: 0.5, stiffness: 0.1, damping: 0.05 }
  },
  {
    id: 'velvet-lux',
    name: 'مخمل فاخر',
    description: 'نسيج ناعم ودافئ بملمس وبري مميز، يضفي فخامة على التصميم.',
    color: '#4a0e0e',
    thickness: 'thick',
    material: 'Velvet',
    image: 'https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?auto=format&fit=crop&q=80&w=300',
    properties: { stretch: 'متوسطة', breathability: 'منخفضة', durability: 'عالية' },
    physics: { mass: 1.1, stiffness: 0.3, damping: 0.4 }
  },
  {
    id: 'wool-merino',
    name: 'صوف ميرينو',
    description: 'صوف ناعم وخفيف الوزن، يوفر عزلاً حرارياً ممتازاً.',
    color: '#D2B48C',
    thickness: 'thick',
    material: 'Wool',
    image: 'https://images.unsplash.com/photo-1579621970583-05f3e3de78d8?auto=format&fit=crop&q=80&w=300',
    properties: { stretch: 'متوسطة', breathability: 'عالية', durability: 'عالية' },
    physics: { mass: 1.2, stiffness: 0.4, damping: 0.3 }
  },
  {
    id: 'linen-pure',
    name: 'كتان طبيعي',
    description: 'نسيج قوي ومتين، مثالي للأجواء الحارة بفضل مساميته العالية.',
    color: '#E8DCCA',
    thickness: 'medium',
    material: 'Linen',
    image: 'https://images.unsplash.com/photo-1620799140408-ed5341cd2431?auto=format&fit=crop&q=80&w=300',
    properties: { stretch: 'منعدمة', breathability: 'عالية جداً', durability: 'عالية' },
    physics: { mass: 0.9, stiffness: 0.8, damping: 0.2 }
  }
];

export const INITIAL_COLORS: FabricColor[] = [
  { id: 'c1', name: 'أسود كلاسيكي', hex: '#000000', category: 'BASIC' },
  { id: 'c2', name: 'أبيض نقي', hex: '#FFFFFF', category: 'BASIC' },
  { id: 'c3', name: 'كحلي', hex: '#1a237e', category: 'BASIC' },
  { id: 'c4', name: 'رمادي غامق', hex: '#424242', category: 'NEUTRAL' },
  { id: 'c5', name: 'بيج', hex: '#f5f5dc', category: 'NEUTRAL' },
  { id: 'c6', name: 'بني جملي', hex: '#c19a6b', category: 'NEUTRAL' },
  { id: 'c7', name: 'أحمر قاني', hex: '#b71c1c', category: 'VIBRANT' },
  { id: 'c8', name: 'أخضر زمردي', hex: '#2e7d32', category: 'VIBRANT' },
  { id: 'c9', name: 'أزرق ملكي', hex: '#1565c0', category: 'VIBRANT' },
  { id: 'c10', name: 'ذهبي', hex: '#ffd700', category: 'METALLIC' },
  { id: 'c11', name: 'فضي', hex: '#c0c0c0', category: 'METALLIC' },
];

export const PATTERNS: PatternDesign[] = [
  { id: 'p1', name: 'سادة', type: 'PLAIN', preview: 'https://placehold.co/100x100/transparent/png?text=Plain' },
  { id: 'p2', name: 'مخطط طولي', type: 'STRIPED', preview: 'https://placehold.co/100x100/transparent/png?text=Stripes' },
  { id: 'p3', name: 'كاروهات', type: 'STRIPED', preview: 'https://placehold.co/100x100/transparent/png?text=Check' },
  { id: 'p4', name: 'زهور ناعمة', type: 'FLORAL', preview: 'https://placehold.co/100x100/transparent/png?text=Floral' },
];

export const INITIAL_STYLES: StyleItem[] = [
  { id: GarmentStyle.SHIRT, label: 'قميص كلاسيك', icon: '👔', description: 'قميص رسمي بياقة وأزرار', occasion: 'FORMAL', season: 'ALL', gender: Gender.MALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Shirt' },
  { id: GarmentStyle.PANTS, label: 'بنطلون رسمي', icon: '👖', description: 'بنطلون بقصة مستقيمة', occasion: 'FORMAL', season: 'ALL', gender: Gender.MALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Pants' },
  { id: GarmentStyle.SUIT, label: 'بدلة كاملة', icon: '🕴️', description: 'طقم جاكيت وبنطلون رسمي', occasion: 'FORMAL', season: 'WINTER', gender: Gender.MALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Suit' },
  { id: GarmentStyle.T_SHIRT, label: 'تيشيرت', icon: '👕', description: 'تيشيرت قطني مريح', occasion: 'DAILY', season: 'SUMMER', gender: Gender.MALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=T-Shirt' },
  { id: GarmentStyle.DRESS, label: 'فستان يومي', icon: '👗', description: 'فستان مريح للاستخدام اليومي', occasion: 'DAILY', season: 'SUMMER', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Dress' },
  { id: GarmentStyle.EVENING_GOWN, label: 'فستان سهرة', icon: '💃', description: 'فستان طويل للمناسبات', occasion: 'EVENING', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Evening+Gown' },
  { id: GarmentStyle.ABAYA, label: 'عباية', icon: '🧕', description: 'عباية تقليدية أنيقة', occasion: 'DAILY', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Abaya' },
  { id: GarmentStyle.BLOUSE, label: 'بلوزة', icon: '👚', description: 'بلوزة أنيقة للعمل', occasion: 'FORMAL', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Blouse' },
  { id: GarmentStyle.SKIRT, label: 'تنورة', icon: '🩰', description: 'تنورة ميدي أو طويلة', occasion: 'FORMAL', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Skirt' },
  
  // Children Styles
  { id: GarmentStyle.KIDS_SUIT, label: 'بدلة أطفال', icon: '🧸', description: 'طقم رسمي للأطفال', occasion: 'CEREMONY', season: 'ALL', gender: Gender.CHILDREN, image: 'https://placehold.co/400x600/1e293b/FFF?text=Kids+Suit' },
  { id: GarmentStyle.DRESS, label: 'فستان أطفال', icon: '👗', description: 'فستان بناتي مريح', occasion: 'DAILY', season: 'SUMMER', gender: Gender.CHILDREN, image: 'https://placehold.co/400x600/1e293b/FFF?text=Kids+Dress' },
  { id: GarmentStyle.T_SHIRT, label: 'طقم كاجوال', icon: '👕', description: 'ملابس لعب مريحة', occasion: 'DAILY', season: 'SUMMER', gender: Gender.CHILDREN, image: 'https://placehold.co/400x600/1e293b/FFF?text=Kids+Casual' },

  { id: GarmentStyle.HOODIE, label: 'هودي', icon: '🧥', description: 'سترة بغطاء رأس رياضية', occasion: 'SPORTS', season: 'WINTER', gender: Gender.MALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Hoodie' },
  { id: GarmentStyle.JUMPSUIT, label: 'جمبسوت', icon: '🕴️', description: 'قطعة واحدة عصرية', occasion: 'EVENING', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Jumpsuit' },
  { id: GarmentStyle.KAFTAN, label: 'قفطان', icon: '👘', description: 'قفطان مغربي أو خليجي', occasion: 'CEREMONY', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Kaftan' },
  { id: GarmentStyle.PLEATED_SKIRT, label: 'تنورة بليسيه', icon: '🩰', description: 'تنورة بطيات متعددة', occasion: 'DAILY', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Pleated+Skirt' },
  { id: GarmentStyle.MERMAID_DRESS, label: 'فستان حورية البحر', icon: '🧜‍♀️', description: 'فستان ضيق يتسع من الأسفل', occasion: 'EVENING', season: 'ALL', gender: Gender.FEMALE, image: 'https://placehold.co/400x600/1e293b/FFF?text=Mermaid' },
];

export const INITIAL_PRICING: PricingRule[] = [
  { styleId: GarmentStyle.SHIRT, basePrice: 200, fabricMultipliers: { 'silk-satin': 1.5, 'cotton-egyptian': 1.2 } },
  { styleId: GarmentStyle.PANTS, basePrice: 180, fabricMultipliers: { 'wool-merino': 1.4, 'linen-pure': 1.3 } },
  { styleId: GarmentStyle.SUIT, basePrice: 800, fabricMultipliers: { 'wool-merino': 1.5 } },
  { styleId: GarmentStyle.EVENING_GOWN, basePrice: 1200, fabricMultipliers: { 'silk-satin': 2.0, 'velvet-lux': 1.8 } },
  { styleId: GarmentStyle.ABAYA, basePrice: 350, fabricMultipliers: { 'silk-satin': 1.3 } },
  { styleId: GarmentStyle.KIDS_SUIT, basePrice: 300, fabricMultipliers: { 'cotton-egyptian': 1.1 } },
];

export const INITIAL_USERS: User[] = [
  { id: 'admin1', username: 'loay94an1@gmail.com', password: '12345677', role: UserRole.ADMIN, referralCode: 'K9L2M4' }
];
